version: "3.8"

services:
  DailyhotApi:
    build:
      context: .
      target: runner
    ports:
      - "80:80"
    volumes:
      - "./logs:/app/logs"
    environment:
      - PORT=80
    user: "114514"
    restart: always
